services:
   backend:
    build:
      context: ../../backend
      dockerfile: ../../container/dockerfiles/backend.ci.Dockerfile
    image: snms-wallet-service:ci
    container_name: snms-wallet-ci
    expose:
      - "8083"
    volumes:
      - ../../backend/appsettings.Development.json:/app/appsettings.Development.json:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8083
    networks:
      - likesub-network

networks:
  likesub-network:
    driver: bridge
    name: likesub-ci-network
