services:
   backend:
    build:
      context: ../../backend
      dockerfile: ../../container/dockerfiles/backend.ci.Dockerfile
    image: backend:ci
    container_name: likesub-backend-ci
    expose:
      - "8080"
    volumes:
      - ../../backend/appsettings.Development.json:/app/appsettings.Development.json:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    networks:
      - likesub-network

networks:
  likesub-network:
    driver: bridge
    name: likesub-ci-network
