services:
  # Backend
  api-gateway:
    image: minhtri269/likesub-backend:dev-latest
    container_name: likesub-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ../../backend:/app
      - backend_bin:/app/bin
      - backend_obj:/app/obj
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: "true"
    command: dotnet watch --project backend.csproj run --no-launch-profile
    depends_on:
      - mysql-db
      - redis
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1GB
        reservations:
          cpus: 1
          memory: 512MB
    networks:
      - likesub-network
    restart: unless-stopped

  

  # REDIS - Cache 
  redis:
    image: redis:7-alpine
    container_name: likesub-redis-dev
    ports:
      - "6379:6379"          
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - likesub-network
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 512MB
        reservations:
          cpus: 0.25
          memory: 256MB
    restart: unless-stopped

  # Database: SQL Server
  mysql-db:
    image: mysql:8.0
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"          
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ../script/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 1GB
        reservations:
          cpus: 0.5
          memory: 512MB
    networks:
      - snms-network

  #  phpMyAdmin — optional dev tool
  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin_dev
    ports:
      - "8070:80"
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: root
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64M
        reservations:
          cpus: 0.25
          memory: 32M
    networks:
      - likesub-network
#=============================================================
networks:
  likesub-network:
    driver: bridge
    name: likesub-dev-network

volumes:
  backend_bin:
    name: backend_bin
  backend_obj:
    name: backend_obj
  mysql_data_dev:
    name: mysql_data_dev
  redis_data:
    name: redis_data